#!/bin/bash
yum install -y httpd
sudo yum -y update
sudo yum install python3
sudo yum install python3-pip3
easy_install pip
python3 -m pip install -U --force-reinstall pip
pip3 install -r /home/ec2-user/sample-app/requirements.txt
